
arm0:
  _target_: manimo.actuators.arms.kinova_arm.KinovaArm
  arm_cfg:
    hz: 30
    name: "KinovaArm"
    # home: [10.66, 14.49, 132.32, 268.08, 329.64, 103.39] # kinova home
    home: [8.1, 14.74, 120.81, 269.45, 299.86, 103.36] # kinova home
    action_space: Cartesian # (Cartesian, Joint)
    delta: False
