cam0:
  _target_: manimo.sensors.real_sense_camera.RealSenseCam
  camera_cfg:
      img_width: 640
      img_height: 480
      hz: 30
      name: "cam0c"
      device_id: "948122073038"
      window_dur: null  # number of seconds to track in buffer
      warm_start:
        enabled: True
        frames: 60